/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/HCf4unaaU3g
 */
import { HoverCardTrigger, HoverCard } from "@/components/ui/hover-card";
import Image from "next/image";

const HovercardV2 = (props) => {
  return (
    <HoverCard>
      <HoverCardTrigger asChild>
        <div className="relative h-36 w-36 overflow-hidden rounded-lg">
          <Image
            alt="Image"
            className="h-full w-full rounded-lg object-cover transition-none hover:scale-105"
            height={300}
            src={props.image}
            style={{
              aspectRatio: "300/300",
              objectFit: "cover",
            }}
            width={300}
          />
          <div className="absolute inset-x-0 bottom-0 flex flex-col items-center justify-center bg-black/60 p-4 text-white opacity-0 transition-opacity duration-200 ease-in-out hover:opacity-50">
            <div className="flex items-center space-x-4">
              <p className="font-small">{props.name}</p>
            </div>
          </div>
        </div>
      </HoverCardTrigger>
    </HoverCard>
  );
};

export default HovercardV2;

// function ImageIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <rect width="18" height="18" x="3" y="3" rx="2" ry="2" />
//       <circle cx="9" cy="9" r="2" />
//       <path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21" />
//     </svg>
//   );
// }
